
builtins = [
  # fields
  'currentAddress',
  'currentHighlight',
  'currentLocation',
  'currentProgram',
  'currentSelection',
  'monitor',
  'propertiesFileParams',
  'state',
  'this',
  # methods
  'askAddress',
  'askAddress',
  'askChoices',
  'askChoices',
  'askProgram',
  'askProgram',
  'askString',
  'askString',
  'clearBackgroundColor',
  'clearBackgroundColor',
  'clearListing',
  'clearListing',
  'clearListing',
  'clearListing',
  'createAsciiString',
  'createAsciiString',
  'createEquate',
  'createEquate',
  'createExternalReference',
  'createExternalReference',
  'createExternalReference',
  'createFragment',
  'createFragment',
  'createFragment',
  'createFragment',
  'createLabel',
  'createLabel',
  'createLabel',
  'createMemoryBlock',
  'createMemoryBlock',
  'createMemoryReference',
  'createMemoryReference',
  'createProgram',
  'createProgram',
  'createProgram',
  'createSymbol',
  'createSymbol',
  'createTableChooserDialog',
  'createTableChooserDialog',
  'find',
  'find',
  'find',
  'findBytes',
  'findBytes',
  'findBytes',
  'findBytes',
  'findBytes',
  'getDataAfter',
  'getDataAfter',
  'getDataBefore',
  'getDataBefore',
  'getEquate',
  'getEquate',
  'getFirstInstruction',
  'getFirstInstruction',
  'getFunctionAfter',
  'getFunctionAfter',
  'getFunctionBefore',
  'getFunctionBefore',
  'getInstructionAfter',
  'getInstructionAfter',
  'getInstructionBefore',
  'getInstructionBefore',
  'getMemoryBlock',
  'getMemoryBlock',
  'getReference',
  'getReference',
  'getSymbolAfter',
  'getSymbolAfter',
  'getSymbolAt',
  'getSymbolAt',
  'getSymbolAt',
  'getSymbolBefore',
  'getSymbolBefore',
  'goTo',
  'goTo',
  'goTo',
  'parseChoices',
  'parseChoices',
  'println',
  'println',
  'removeEquate',
  'removeEquate',
  'runCommand',
  'runCommand',
  'runScript',
  'runScript',
  'runScript',
  'runScript',
  'saveProgram',
  'saveProgram',
  'setBackgroundColor',
  'setBackgroundColor',
  'setReferencePrimary',
  'setReferencePrimary',
  'show',
  'show',
  'toAddr',
  'toAddr',
  'toAddr',
  'toHexString',
  'toHexString',
  'toHexString',
  'toHexString',
  'addEntryPoint',
  'addInstructionXref',
  'analyze',
  'analyzeAll',
  'analyzeChanges',
  'askBytes',
  'askChoice',
  'askDirectory',
  'askDomainFile',
  'askDouble',
  'askFile',
  'askInt',
  'askLanguage',
  'askLong',
  'askPassword',
  'askProjectFolder',
  'askValues',
  'askYesNo',
  'cleanup',
  'closeProgram',
  'createAddressSet',
  'createBookmark',
  'createByte',
  'createChar',
  'createClass',
  'createDWord',
  'createData',
  'createDouble',
  'createDwords',
  'createFloat',
  'createFunction',
  'createHighlight',
  'createNamespace',
  'createQWord',
  'createSelection',
  'createStackReference',
  'createUnicodeString',
  'createWord',
  'disassemble',
  'end',
  'execute',
  'findPascalStrings',
  'findStrings',
  'getAddressFactory',
  'getAnalysisOptionDefaultValue',
  'getAnalysisOptionDefaultValues',
  'getAnalysisOptionDescription',
  'getAnalysisOptionDescriptions',
  'getBookmarks',
  'getByte',
  'getBytes',
  'getCategory',
  'getCodeUnitFormat',
  'getCurrentAnalysisOptionsAndValues',
  'getCurrentProgram',
  'getDataAt',
  'getDataContaining',
  'getDataTypes',
  'getDefaultLanguage',
  'getDemangled',
  'getDouble',
  'getEOLComment',
  'getEOLCommentAsRendered',
  'getEquates',
  'getFirstData',
  'getFirstFunction',
  'getFloat',
  'getFragment',
  'getFunction',
  'getFunctionAt',
  'getFunctionContaining',
  'getGhidraVersion',
  'getGlobalFunctions',
  'getInstructionAt',
  'getInstructionContaining',
  'getInt',
  'getLanguage',
  'getLastData',
  'getLastFunction',
  'getLastInstruction',
  'getLong',
  'getMemoryBlocks',
  'getMonitor',
  'getNamespace',
  'getPlateComment',
  'getPlateCommentAsRendered',
  'getPostComment',
  'getPostCommentAsRendered',
  'getPreComment',
  'getPreCommentAsRendered',
  'getProgramFile',
  'getProjectRootFolder',
  'getReferencesFrom',
  'getReferencesTo',
  'getRepeatableComment',
  'getRepeatableCommentAsRendered',
  'getReusePreviousChoices',
  'getScriptAnalysisMode',
  'getScriptArgs',
  'getScriptName',
  'getShort',
  'getSourceFile',
  'getState',
  'getSymbol',
  'getSymbols',
  'getUndefinedDataAfter',
  'getUndefinedDataAt',
  'getUndefinedDataBefore',
  'getUserName',
  'importFile',
  'importFileAsBinary',
  'isAnalysisOptionDefaultValue',
  'isRunningHeadless',
  'openDataTypeArchive',
  'openProgram',
  'parseAddress',
  'parseBoolean',
  'parseBytes',
  'parseChoice',
  'parseDirectory',
  'parseDomainFile',
  'parseDouble',
  'parseFile',
  'parseInt',
  'parseLanguageCompileSpecPair',
  'parseLong',
  'parseProjectFolder',
  'popup',
  'printerr',
  'printf',
  'removeBookmark',
  'removeData',
  'removeDataAt',
  'removeEntryPoint',
  'removeEquates',
  'removeFunction',
  'removeFunctionAt',
  'removeHighlight',
  'removeInstruction',
  'removeInstructionAt',
  'removeMemoryBlock',
  'removeReference',
  'removeSelection',
  'removeSymbol',
  'resetAllAnalysisOptions',
  'resetAnalysisOption',
  'resetAnalysisOptions',
  'run',
  'runScriptPreserveMyState',
  'setAnalysisOption',
  'setAnalysisOptions',
  'setAnonymousServerCredentials',
  'setByte',
  'setBytes',
  'setCurrentHighlight',
  'setCurrentLocation',
  'setCurrentSelection',
  'setDouble',
  'setEOLComment',
  'setFloat',
  'setInt',
  'setLong',
  'setPlateComment',
  'setPostComment',
  'setPotentialPropertiesFileLocations',
  'setPreComment',
  'setPropertiesFile',
  'setPropertiesFileLocation',
  'setRepeatableComment',
  'setReusePreviousChoices',
  'setScriptArgs',
  'setServerCredentials',
  'setShort',
  'setSourceFile',
  'setToolStatusMessage',
  'start',
  'toString',
]
